apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-helm
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        global:
          name: fmt2
          datacenter: fmt2