apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: 'true'
  namespace: grafana
stringData:
  datasources.yaml: |-
   apiVersion: 1
   datasources:
    - name: VM-FMT2
      type: prometheus
      access: proxy
      orgId: 1
      url: http://vmselect.fmt2.generalprogramming.org:8481/select/0/prometheus
      editable: false
    - name: VM-SEA1
      type: prometheus
      access: proxy
      orgId: 1
      url: http://vmselect.sea1.generalprogramming.org:8481/select/0/prometheus
      editable: false
    - name: VM-OCI
      type: prometheus
      access: proxy
      orgId: 1
      url: http://10.1.1.132:8428
      editable: false
    - name: Loki-FMT2
      type: loki
      access: proxy
      orgId: 1
      url: http://loki-helm-gateway.loki.svc.cluster.local
      editable: false
    - name: Tempo-FMT2
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo-helm-gateway.tempo.svc.cluster.local
      editable: false
