apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-render-server
spec:
  selector:
    matchLabels:
      app: html-render-server
  replicas: 1
  template:
    metadata:
      labels:
        app: html-render-server
    spec:
      containers:
      - name: server
        image: ghcr.io/general-programming/megarepo/html_render_server:latest@sha256:a04b4aebce9b89a808e1cd8333c2ce9aca9619a366a99948f08604b84b79dae1
        command:
          - python3
          - api.py
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: html-render-server-secrets
              key: api_key
        - name: CDN_URL
          valueFrom:
            secretKeyRef:
              name: html-render-server-secrets
              key: cdn_url
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: html-render-server-secrets
              key: s3_bucket
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: html-render-server-secrets
              key: s3_endpoint
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: html-render-server-secrets
              key: s3_access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: html-render-server-secrets
              key: s3_secret_key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: html-render-server-secrets
              key: sentry_dsn
        ports:
        - containerPort: 8080
