apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-html-render-server
spec:
  type: kv-v2
  mount: secret
  path: app/html-render-server
  destination:
    name: html-render-server-secrets
    create: true
  refreshAfter: 30s
