apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: victoriametrics
spec:
  selectAllByDefault: true
  replicaCount: 1
  remoteWrite:
    - url: "http://vminsert-fmt2-victoriametrics.victoriametrics.svc.generalprogramming.org:8480/insert/0/prometheus/api/v1/write"