apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: fmt2-victoriametrics
spec:
  # Add fields here
  retentionPeriod: "4"
  replicationFactor: 2
  vmstorage:
    replicaCount: 2
    storageDataPath: "/vm-data"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-rbd
          resources:
            requests:
              storage: 128Gi
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
  vmselect:
    replicaCount: 2
    cacheMountPath: "/select-cache"
    storage:
      volumeClaimTemplate:
        storageClassName: ceph-rbd
        spec:
          resources:
            requests:
              storage: 2Gi
    resources:
      limits:
        cpu: "2"
        memory: "1Gi"
  vminsert:
    replicaCount: 2