apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/VictoriaMetrics/operator/config/default?ref=v0.35.1
  - cluster.yaml
  - vmagent.yaml

images:
- name: victoriametrics/operator
  newTag: v0.35.1