---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-env
data:
  SKIP_STARTUP_SCRIPTS: "true"
  DB_WAIT_DEBUG: "1"
  # SECRET_KEY in vault

  # Superuser, secrets
  SUPERUSER_EMAIL: nepeat@generalprogramming.org
  # SUPERUSER_API_TOKEN in vault

  # NAPALM
  NAPALM_USERNAME: netbox
  # NAPALM_PASSWORD in vault

  # Other
  CORS_ORIGIN_WHITELIST: https://netbox.generalprogramming.org
  METRICS_ENABLED: "1"
  WEBHOOKS_ENABLED: "true"
  MEDIA_ROOT: /opt/netbox/netbox/media

  # Redis
  REDIS_HOST: netbox-redis

  # LDAP - Connection, Bind
  REMOTE_AUTH_ENABLED: "true"
  REMOTE_AUTH_BACKEND: netbox.authentication.LDAPBackend
  AUTH_LDAP_SERVER_URI: ldap://ipa.generalprogramming.org
  AUTH_LDAP_BIND_DN: uid=netbox,cn=users,cn=accounts,dc=ipa,dc=generalprogramming,dc=org
  # AUTH_LDAP_BIND_PASSWORD in vault
  LDAP_IGNORE_CERT_ERRORS: "true"

  # LDAP - User DNs
  AUTH_LDAP_USER_SEARCH_BASEDN: cn=users,cn=accounts,dc=ipa,dc=generalprogramming,dc=org
  AUTH_LDAP_USER_SEARCH_ATTR: uid

  # LDAP - Group DNs
  AUTH_LDAP_REQUIRE_GROUP: ipausers
  AUTH_LDAP_GROUP_SEARCH_BASEDN: cn=groups,cn=accounts,dc=ipa,dc=generalprogramming,dc=org
  AUTH_LDAP_GROUP_SEARCH_CLASS: groupOfNames

  # LDAP - Special groups
  AUTH_LDAP_REQUIRE_GROUP_DN: cn=ipausers,cn=groups,cn=accounts,dc=ipa,dc=generalprogramming,dc=org
  AUTH_LDAP_IS_ADMIN_DN: cn=admins,cn=groups,cn=accounts,dc=ipa,dc=generalprogramming,dc=org
  AUTH_LDAP_IS_SUPERUSER_DN: cn=superadmins,cn=groups,cn=accounts,dc=ipa,dc=generalprogramming,dc=org

  NETBOX_DELETE_LEGACY_DATA: "1"
