---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-bookworm
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 2Gi
  bootstrap:
    initdb:
      database: netbox
      owner: netbox
