apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
resources:
  - env.yaml
  - config.yaml
  - database.yaml
  - redis.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
