---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media
  labels:
    app.kubernetes.io/component: netbox-media
    app.kubernetes.io/name: netbox
spec:
  storageClassName: cephfs
  # Your storage class may not have ReadWriteMany.
  # If it does not, setting it to ReadWriteOnce is fine.
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
