---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-timescaledb
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: timescale
    major: 17
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 256Gi
  bootstrap:
    initdb:
      database: shared
      owner: shared
  postgresUID: 1000
  postgresGID: 1000
  postgresql:
    shared_preload_libraries:
      - timescaledb
