apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: vault
    helm:
      valuesObject:
        global:
          enabled: false
          tlsDisable: false
          externalVaultAddr: 'https://vault-proxy-v4.catgirls.dev:8200'

        csi:
          enabled: true

        injector:
          enabled: true
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.29.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - allowEmpty=true
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
      name: vault-helm-agent-injector-cfg
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
