apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator-helm
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: vault-secrets-operator
    helm:
      valuesObject:
        defaultVaultConnection:
          enabled: true
          address: 'https://vault-proxy.catgirls.dev:8200'

        defaultAuthMethod:
          enabled: true
          kubernetes:
            role: k8s-read
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.5.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - allowEmpty=true
  # ignoreDifferences:
  #   - group: "admissionregistration.k8s.io"
  #     kind: MutatingWebhookConfiguration
  #     name: vault-helm-agent-injector-cfg
  #     jqPathExpressions:
  #       - .webhooks[].clientConfig.caBundle
