apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  ports:
  - port: 6667
    targetPort: 6667
  - port: 6697
    targetPort: 6697
  selector:
    app: znc
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: znc-external
  annotations:
    metallb.universe.tf/address-pool: fmt2-pool-external
    metallb.universe.tf/allow-shared-ip: external
spec:
  ports:
  - port: 16969
    targetPort: 6697
  selector:
    app: znc
  type: LoadBalancer