---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KC_HTTP_ENABLED: "true"
  KEYCLOAK_PROXY: "edge"
  KEYCLOAK_FEATURES: "token-exchange"
  KEYCLOAK_DB_HOST: primary.16-sea1.service.consul
  KC_METRICS_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KEYCLOAK_HOSTNAME: sso.generalprogramming.org
  KC_PROXY_HEADERS: xforwarded
  KC_HTTPS_KEY_STORE_FILE: /certs/keystore.jks