---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secret
spec:
  type: kv-v2
  mount: secret
  path: app/postgres_secrets
  destination:
    name: postgres-secret
    create: true
  refreshAfter: 1m
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 2Gi
  bootstrap:
    # initdb:
    #   database: keycloak
    #   owner: keycloak
    #   secret:
    #     name: keycloak-db-secret
    pg_basebackup:
      source: source-db
      database: keycloak
      owner: keycloak
  externalClusters:
  - name: source-db
    connectionParameters:
      host: primary.16-sea1.service.consul
      user: superadmin
      dbname: keycloak
      port: "5433"
    password:
      name: postgres-secret
      key: password
