apiVersion: v1
kind: Namespace
metadata:
  name: ceph
  labels:
    kubernetes.io/metadata.name: ceph
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest