apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ceph.yaml
  - loki.yaml
  - traefik.yaml
  - consul.yaml
  - vault.yaml
  - external-dns.yaml
  - grafana-operator.yaml

  # apps
  - registry.yaml
  - grafana.yaml