apiVersion: v1
kind: Namespace
metadata:
  name: loki
  labels:
    kubernetes.io/metadata.name: loki
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest