apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    kubernetes.io/metadata.name: vault
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest