apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  ports:
  - port: 6667
    targetPort: 6667
    name: irc
  - port: 6697
    targetPort: 6697
    name: ircs
  selector:
    app: znc
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: znc-external
spec:
  ports:
  - port: 16969
    targetPort: 6697
    name: ircs
  selector:
    app: znc
  type: LoadBalancer