apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.13.5

resources:
  - secrets.yaml
  - ./external-dns-deployment.yaml
  - ./external-dns-serviceaccount.yaml
  - ./external-dns-clusterrole.yaml
  - ./external-dns-clusterrolebinding.yaml
