apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator-helm
  namespace: argocd
spec:
  destination:
    namespace: mariadb-operator
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: mariadb-operator
    repoURL: https://mariadb-operator.github.io/mariadb-operator
    targetRevision: v0.36.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - allowEmpty=true
      - ServerSideApply=true
