apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-config
data:
  TZ: UTC
  PUID: "1000"
  PGID: "1000"
  LIBRENMS_POLLER_INTERVAL: "3"
  LIBRENMS_BASE_URL: https://nms.generalprogramming.org
  REDIS_HOST: librenms-redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  CACHE_DRIVER: "redis"
  RRDCACHED_SERVER: "rrdcached:42217"
  # DB in k8s
  DB_HOST: mariadb-librenms
  DB_NAME: librenms
  DB_USER: librenms
