---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-librenms
spec:
  replicas: 3
  galera:
    enabled: true
    config:
      reuseStorageVolume: true
  username: librenms
  passwordSecretKeyRef:
    name: db-password
    key: librenms_password
    generate: true
  rootPasswordSecretKeyRef:
    name: db-password
    key: root_password
    generate: true
  database: librenms
  storage:
    size: 16Gi
    storageClassName: local-path
