apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms
spec:
  selector:
    matchLabels:
      app: librenms
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms
    spec:
      containers:
      - name: librenms
        image: nepeat/librenms:latest
        envFrom:
        - configMapRef:
            name: librenms-config
        - secretRef:
            name: librenms-secrets

        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-dispatcher
spec:
  selector:
    matchLabels:
      app: librenms-dispatcher
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms-dispatcher
    spec:
      containers:
      - name: librenms
        image: nepeat/librenms:latest
        envFrom:
        - configMapRef:
            name: librenms-config
        - secretRef:
            name: librenms-secrets
        env:
        - name: SIDECAR_DISPATCHER
          value: "1"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data
---
