apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-redis
spec:
  selector:
    matchLabels:
      app: librenms
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms
    spec:
      containers:
      - name: redis
        image: redis:alpine
