apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms-redis
spec:
  selector:
    matchLabels:
      app: librenms-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms-redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms
spec:
  selector:
    matchLabels:
      app: librenms
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms
    spec:
      dnsPolicy: Default
      containers:
      - name: librenms
        image: librenms/librenms:latest
        envFrom:
        - configMapRef:
            name: librenms-config
        - secretRef:
            name: librenms-secrets

        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        persistentVolumeClaim:
          claimName: librenms-data
