apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro
spec:
  selector:
    matchLabels:
      app: cerebro
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - name: cerebro
        image: ghcr.io/general-programming/cerebro:main
