apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-keycloak
spec:
  type: kv-v2
  mount: secret
  path: app/keycloak
  destination:
    name: keycloak-secrets
    create: true
  refreshAfter: 1m
