apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        service:
          ipFamilies:
          - IPv6
          annotations:
            metallb.universe.tf/address-pool: pool-external
            metallb.universe.tf/allow-shared-ip: external
---