apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress_argo.yaml
  - ingress_dashboard.yaml
# TODO: Fix MetalLB for IPv6 only.
# patches:
#   - path: application.yaml