apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator-helm
  namespace: argocd
spec:
  destination:
    namespace: grafana-operator
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: grafana-agent-operator
    helm:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.4.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - allowEmpty=true
      - ServerSideApply=true
