---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: carstore-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.1
  instances: 1
  postgresql:
    parameters:
      shared_buffers: "1024MB"
      work_mem: "16MB"
      max_wal_size: "4GB"
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: ceph-rbd-xfs
    size: 1024Gi
  bootstrap:
    initdb:
      database: carstore
      owner: carstore
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bgs-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.1
  instances: 1
  postgresql:
    parameters:
      shared_buffers: "2048MB"
      work_mem: "16MB"
      max_wal_size: "4GB"
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: ceph-rbd-xfs
    size: 1024Gi
  bootstrap:
    initdb:
      database: bgs
      owner: bgs
