apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bsky-relay
resources:
  - ../base
  - database.yaml
  - ingress.yaml
  - secret.yaml
patches:
  - path: patch-config.yaml
  - path: patch-deployment.yaml
