---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
spec:
  template:
    spec:
      containers:
        - name: relay
          env:
            - name: CARSTORE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: carstore-db-app
                  key: uri
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bgs-db-app
                  key: uri