apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-atproto-relay
spec:
  type: kv-v2
  mount: secret
  path: app/atproto-relay-sea1
  destination:
    name: relay-secrets
    create: true
  refreshAfter: 1m
