apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-atproto-relay
  labels:
    app.kubernetes.io/component: atproto-relay
    app.kubernetes.io/name: atproto
spec:
  type: kv-v2
  mount: secret
  path: app/atproto-relay-sea1
  destination:
    name: relay-secrets
    create: true
  refreshAfter: 1m
