---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: docspell-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.5
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 4Gi
  bootstrap:
    initdb:
      database: docspell
      owner: docspell
