apiVersion: v1
kind: Service
metadata:
  name: docspell-restserver
spec:
  selector:
    app: docspell-restserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: docspell-joex
spec:
  selector:
    app: docspell-joex
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7878
  type: ClusterIP