---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mastodon-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-bookworm
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 2Gi
  bootstrap:
    initdb:
      database: mastodon
      owner: mastodon
      import:
        type: microservice
        databases:
          - mastodon
  postgresql:
    parameters:
      max_connections: "256"
      shared_buffers: "1GB"
