---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mastodon-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.5
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 2Gi
  bootstrap:
    initdb:
      database: mastodon
      owner: mastodon
      import:
        type: microservice
        databases:
          - mastodon
