apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon-coolmathgames
resources:
  - "database.yaml"
helmCharts:
  - name: mastodon
    releaseName: mastodon
    repo: https://small-hack.github.io/mastodon-helm-chart
    version: 9.8.2
    valuesFile: mastodon-values.yaml
