apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: secrets-store-csi-driver
    releaseName: secrets-store-csi-driver
    version: 1.4.8
    repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts