apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: traefik
    helm:
      valuesObject:
        deployment:
          kind: DaemonSet
          updateStrategy:
            type: RollingUpdate
        dashboard:
          enabled: false
        logs:
          access:
            enabled: true
            format: json
        additionalArguments:
          - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik-helm"
    repoURL: https://traefik.github.io/charts
    targetRevision: 32.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - allowEmpty=true
