apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tunnel-credentials
spec:
  type: kv-v2
  mount: secret
  path: app/sea1-cloudflared-traefik
  destination:
    name: tunnel-credentials
    create: true
  refreshAfter: 1m
