apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  labels:
    kubernetes.io/metadata.name: local-path-storage
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest