apiVersion: v1
kind: Namespace
metadata:
  name: shared-db
  labels:
    kubernetes.io/metadata.name: shared-db
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
