apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    kubernetes.io/metadata.name: traefik
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest