apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-netbox
spec:
  type: kv-v2
  mount: secret
  path: app/netbox
  destination:
    name: netbox-secrets
    create: true
  refreshAfter: 1m
