apiVersion: v1
kind: Namespace
metadata:
  name: consul
  labels:
    kubernetes.io/metadata.name: consul
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest