apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-docspell
spec:
  type: kv-v2
  mount: secret
  path: app/docspell-sea1
  destination:
    name: docspell-secrets
    create: true
  refreshAfter: 1m
