apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-genprog
spec:
  secretName: tls-secret
  issuerRef: 
    kind: Issuer
    name: letsencrypt-genprog
  dnsNames:
    - "generalprogramming.org"
    - "*.generalprogramming.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-catgirls
spec:
  secretName: tls-secret
  issuerRef: 
    kind: Issuer
    name: letsencrypt-genprog
  dnsNames:
    - "catgirls.dev"
    - "*.catgirls.dev"