---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sentry-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-bookworm
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: local-path
    size: 16Gi
  bootstrap:
    initdb:
      database: sentry
      owner: sentry
