---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sentry-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-bookworm
  instances: 2
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
      storageClassName: local-path
      persistentVolumeReclaimPolicy: Retain
  bootstrap:
    initdb:
      database: sentry
      owner: sentry
  postgresql:
    parameters:
      max_connections: "284"
      shared_buffers: "1GB"