---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: sentry
    releaseName: sentry
    namespace: sentry
    repo: https://sentry-kubernetes.github.io/charts
    version: v26.14.0
    valuesFile: values.yaml