apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/VictoriaMetrics/operator/config/default?ref=v0.41.1
  - agent_scrape_pod.yaml
  - agent_scrape_service.yaml
images:
- name: victoriametrics/operator
  newTag: v0.41.0