apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoriametrics
resources:
  - github.com/VictoriaMetrics/operator/config/base?ref=v0.58.0
  - agent_scrape_pod.yaml
  - agent_scrape_service.yaml
  - agent_scrape_state_metrics.yaml
  - agent_scrape_kubelet.yaml
  - agent_scrape_node_exporter.yaml
images:
- name: manager
  newName: victoriametrics/operator
  newTag: v0.58.0
# IDK how to do this properly.
replacements:
- source:
    fieldPath: .metadata.namespace
    group: cert-manager.io
    kind: Certificate
    name: vm-serving-cert
    version: v1
  targets:
  - fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
    select:
      kind: ValidatingWebhookConfiguration
  - fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
    select:
      kind: CustomResourceDefinition
- source:
    fieldPath: .metadata.name
    group: cert-manager.io
    kind: Certificate
    name: vm-serving-cert
    version: v1
  targets:
  - fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
      index: 1
    select:
      kind: ValidatingWebhookConfiguration
  - fieldPaths:
    - .metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      create: true
      delimiter: /
      index: 1
    select:
      kind: CustomResourceDefinition
- source:
    fieldPath: .metadata.namespace
    kind: Service
    name: webhook-service
    version: v1
  targets:
  - fieldPaths:
    - .spec.dnsNames.0
    - .spec.dnsNames.1
    options:
      create: true
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      version: v1