apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoriametrics
resources:
  - github.com/VictoriaMetrics/operator/config/default?ref=v0.50.0
  - agent_scrape_pod.yaml
  - agent_scrape_service.yaml
  - agent_scrape_state_metrics.yaml
  - agent_scrape_kubelet.yaml
  - agent_scrape_node_exporter.yaml
images:
- name: manager
  newName: victoriametrics/operator
  newTag: v0.50.0
