apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-tempo-secrets
  namespace: tempo
spec:
  type: kv-v2
  mount: secret
  path: app/tempo-secrets
  destination:
    name: tempo-secrets
    create: true
  refreshAfter: 30s
