apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-mail-webhook
spec:
  type: kv-v2
  mount: secret
  path: app/mail-webhook
  destination:
    name: mail-webhook-secrets
    create: true
  refreshAfter: 30s
