apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-librenms
spec:
  type: kv-v2
  mount: secret
  path: app/librenms-sea1
  destination:
    name: librenms-secrets
    create: true
  refreshAfter: 1m
