apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-rook-ceph-mon
  namespace: ceph
spec:
  type: kv-v2
  mount: secret
  path: rook/ceph-mon
  destination:
    name: rook-ceph-mon
    create: false
    type: kubernetes.io/rook
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-rook-csi-rbd-node
  namespace: ceph
spec:
  type: kv-v2
  mount: secret
  path: rook/csi-rbd-node
  destination:
    name: rook-csi-rbd-node
    create: false
    type: kubernetes.io/rook
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-rook-csi-rbd-provisioner
  namespace: ceph
spec:
  type: kv-v2
  mount: secret
  path: rook/csi-rbd-provisioner
  destination:
    name: rook-csi-rbd-provisioner
    create: false
    type: kubernetes.io/rook
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-rook-csi-cephfs-node
  namespace: ceph
spec:
  type: kv-v2
  mount: secret
  path: rook/csi-cephfs-node
  destination:
    name: rook-csi-cephfs-node
    create: false
    type: kubernetes.io/rook
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-rook-csi-cephfs-provisioner
  namespace: ceph
spec:
  type: kv-v2
  mount: secret
  path: rook/csi-cephfs-provisioner
  destination:
    name: rook-csi-cephfs-provisioner
    create: false
    type: kubernetes.io/rook
  refreshAfter: 1m
