apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-mon
  namespace: ceph
type: kubernetes.io/rook
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-node
  namespace: ceph
type: kubernetes.io/rook
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: ceph
type: kubernetes.io/rook
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-node
  namespace: ceph
type: kubernetes.io/rook
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: ceph
type: kubernetes.io/rook