apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  name: argocd-cm
  literals:
  - |
    repository.credentials=- passwordSecret:
        key: git_token
        name: autopilot-secret
      url: https://github.com/
      usernameSecret:
        key: git_username
        name: autopilot-secret
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj-labs/argocd-autopilot/manifests/ha?ref=v0.4.17
- argocd-lb.yaml
patches:
  - path: patch_cm_dex.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: rbac.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: patch_ha.yaml
