apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-helm
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: traefik/traefik
    helm:
      values: |-
        deployment:
          kind: DaemonSet
          updateStrategy:
            type: RollingUpdate
        ports:
          web:
            hostPort: 80
          websecure:
            hostPort: 443
    repoURL: https://traefik.github.io/charts
    targetRevision: 24.0.0
  syncPolicy:
    automated:
      prune: true
