apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot-registry
  namespace: argocd
spec:
  destination:
    namespace: zot-registry
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: zot
    helm:
      values: |-
        service:
          type: LoadBalancer
        persistence: true
        pvc:
          create: true
        configFiles:
          config.json: |-
            {
                "storage": {
                    "rootDirectory": "/var/lib/registry",
                    "dedupe": true,
                    "storageDriver": {
                        "name": "s3",
                        "rootdirectory": "/zot",
                        "region": "us-east-1",
                        "regionendpoint": "http://10.65.67.100",
                        "bucket": "zot-registry",
                        "secure": true,
                        "skipverify": true,
                        "accesskey": "HVGSNLNW4W6Q93XO0UFE",
                        "secretkey": "K0qgSb10mWygblA0z52AaelQ58qhDPx6SFaamUxo"
                    }
                },
                "http": {
                    "address": "0.0.0.0",
                    "port": "5000"
                },
                "log": {
                    "level": "debug"
                }
            }
    repoURL: http://zotregistry.io/helm-charts
    targetRevision: v0.1.26
  syncPolicy:
    automated:
      prune: true
