apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot-registry
  namespace: argocd
spec:
  destination:
    namespace: zot-registry
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: zot
    helm:
      valueFiles:
        - values.yaml
    repoURL: http://zotregistry.io/helm-charts
    targetRevision: v0.1.26
  syncPolicy:
    automated:
      prune: true
