apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://sea1-argo.generalprogramming.org
  dex.config: |
    logger:
      level: debug
    connectors:
    - type: oidc
      id: vault
      name: Vault
      config:
        issuer: https://vault-proxy.catgirls.dev:8200/v1/identity/oidc/provider/default
        clientID: L249EnwdRKhcafylyKuh26JDlcbeGWYL
        clientSecret: hvo_secret_fINi5YbMtMUoSMHSkEc0GnyU8ruR7IuwwdQgW8Hd41PPnQFT4bbUkUSE8bR8lSng
        insecureEnableGroups: true
        insecureSkipEmailVerified: true
        scopes:
        - user
        claimMapping:
          preferred_username: username
          email: username
        userNameKey: username
