---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sentry
spec:
  type: kv-v2
  mount: secret
  path: app/sentry
  destination:
    name: sentry-secrets
    create: true
  refreshAfter: 1m
