apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        global:
          authPath: "auth/kubernetes-sea1"