apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator-helm
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        defaultAuthMethod:
          mount: "kubernetes-sea1"
        defaultVaultConnection:
          enabled: true
          # TODO / HACK: Why does HTTPS not work!!!!
          address: 'http://vault-proxy.catgirls.dev:8201'