apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erin-matrix-helm
  namespace: argocd
  annotations:
      argocd.argoproj.io/sync-options: ApplyOnly=true
spec:
  destination:
    namespace: erin-matrix
    server: https://kubernetes.default.svc
  project: erin-apps
  source:
    repoURL: https://matrix-org.github.io/dendrite
    chart: "dendrite"
    targetRevision: "0.13.5"

    helm:
      valuesObject:
        dendrite_config:
          global:
            server_name: owo.me

            database:
              # TODO: Secret and rotate config...
              connection_string: "postgresql://matrix:244D2BCB-7CBA-450A-8971-93D31E40CEA6@primary.16-sea1.service.consul:5433/matrix"
              max_open_conns: 90
              max_idle_conns: 5
              conn_max_lifetime: -1
            
            persistence:
              enable_inbound: true
              enable_outbound: true
            
            metrics:
              enabled: true
            
            profiling:
              enabled: true

        postgresql:
          enabled: false
            
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            external-dns.alpha.kubernetes.io/target: "sea1-traefik-k8s.generalprogramming.org"
          hostName: matrix.owo.me

        prometheus:
          servicemonitor:
            enabled: true

        grafana:
          dashboards:
            enabled: true
        
        client_api:
          registration_shared_secret: "A9B024FA-9EE9-4682-9C6E-E7CA99C439AE"

  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated: {}
      
