---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: matrix-signing-key
spec:
  type: kv-v2
  mount: secret
  path: app/matrix/signing-key
  destination:
    name: matrix-signing-key
    create: true
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: matrix-secrets
spec:
  type: kv-v2
  mount: secret
  path: app/matrix/secrets
  destination:
    name: matrix-secrets
    create: true
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mas-secrets
spec:
  type: kv-v2
  mount: secret
  path: app/matrix/mas-secrets
  destination:
    name: mas-secrets
    create: true
  refreshAfter: 1m
