apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devhack-librenms
resources:
  - ../../librenms/base
  - ingress.yaml
  - secret.yaml
  - startup-script.yaml
patches:
  - path: config.yaml