---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-startup
data:
  setup-script.sh: |
    #!/bin/bash
    set -x
    
    cd /opt/librenms

    lnms config:set auth.socialite.configs.keycloak.client_id ${KEYCLOAK_CLIENT_ID}
    lnms config:set auth.socialite.configs.keycloak.client_secret ${KEYCLOAK_CLIENT_SECRET}
    # lnms config:set auth.socialite.configs.keycloak.redirect
    lnms config:set auth.socialite.configs.keycloak.base_url https://idp.devhack.net
    lnms config:set auth.socialite.configs.keycloak.realms devhack
    lnms config:set auth.socialite.configs.keycloak.listener "\SocialiteProviders\keycloak/KeycloakExtendSocialite"
