---
apiVersion: v1
kind: Service
metadata:
  name: ipfs
  labels:
    app.kubernetes.io/component: ipfs
    app.kubernetes.io/name: ipfs
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: ipfs
  type: ClusterIP
