---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data
  labels:
    app.kubernetes.io/component: ipfs
    app.kubernetes.io/name: ipfs
spec:
  # Your storage class may not have ReadWriteMany.
  # If it does not, setting it to ReadWriteOnce is fine.
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
