---
apiVersion: v1
kind: ConfigMap
metadata:
  name: relay-config
  labels:
    app.kubernetes.io/component: atproto-relay
    app.kubernetes.io/name: atproto
data:
  DATA_DIR: /data/bigsky
  BGS_SPIDERING: "true"
  # OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.fmt2.generalprogramming.org
