---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
  labels:
    app.kubernetes.io/component: atproto-relay
    app.kubernetes.io/name: atproto
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: relay
  replicas: 1
  template:
    metadata:
      labels:
        app: relay
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "2471"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: relay
        image: ghcr.io/general-programming/megarepo/bigsky:latest
        envFrom:
        - configMapRef:
            name: relay-config
        - secretRef:
            name: relay-secrets
        # I assume that shared data may become possible eventually.
        volumeMounts:
        - name: relay-data
          mountPath: /data
        # Based on the server requirements on the normal server.
        resources:
          requests:
            memory: 48Gi
        ports:
        - containerPort: 2470
          name: http
        - containerPort: 2471
          name: metrics

      volumes:
      - name: relay-data
        persistentVolumeClaim:
          claimName: relay-data