---
apiVersion: v1
kind: Service
metadata:
  name: relay
  labels:
    app.kubernetes.io/component: atproto-relay
    app.kubernetes.io/name: atproto
spec:
  ports:
  - port: 80
    targetPort: 2470
    name: http
  selector:
    app: relay
  type: ClusterIP
