---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-data
  labels:
    app.kubernetes.io/component: atproto-relay
    app.kubernetes.io/name: atproto
spec:
  # Your storage class may not have ReadWriteMany.
  # If it does not, setting it to ReadWriteOnce is fine.
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
