apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-helm
  namespace: argocd
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: loki
    helm:
      valuesObject:
        global:
          clusterDomain: "generalprogramming.org"
        loki:
          auth_enabled: false

          storage:
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            type: s3
            s3:
              endpoint: http://10.65.67.100
              accessKeyId: ${S3_ACCESS_KEY}
              secretAccessKey: ${S3_SECRET_KEY}
              s3ForcePathStyle: false
              insecure: false
          
          schemaConfig:
            configs:
              - from: "2023-08-01"
                store: tsdb
                object_store: s3
                schema: v12
                index:
                  prefix: loki_index_
                  period: 24h

        gateway:
          service:
            type: LoadBalancer
            annotations:
              external-dns.alpha.kubernetes.io/hostname: loki.fmt2.generalprogramming.org

        backend:
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: s3_access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: s3_secret_key

        read:
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: s3_access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: s3_secret_key

        write:
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: s3_access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-secrets
                  key: s3_secret_key
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v5.15.0
  syncPolicy:
    automated:
      prune: true
