apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
configMapGenerator:
- files:
  - config.yaml
  name: loki-config
  options:
    disableNameSuffixHash: true
resources:
  - secrets.yaml
  - application.yaml