apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-loki-secrets
  namespace: loki
spec:
  type: kv-v2
  mount: secret
  path: app/loki-secrets
  destination:
    name: loki-secrets
    create: true
  refreshAfter: 30s
