apiVersion: v1
kind: Service
metadata:
  name: loki
  annotations:
    external-dns.alpha.kubernetes.io/hostname: loki.fmt2.generalprogramming.org
spec:
  ports:
  - port: 3100
    targetPort: 3100
    name: http
  selector:
    app: loki
  type: LoadBalancer