apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mastodon-secrets
spec:
  type: kv-v2
  mount: secret
  path: app/mastodon-coolmathgames/secrets
  destination:
    name: mastodon-secrets
    create: true
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mastodon-smtp
spec:
  type: kv-v2
  mount: secret
  path: app/mastodon-coolmathgames/smtp
  destination:
    name: mastodon-smtp
    create: true
  refreshAfter: 1m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mastodon-s3
spec:
  type: kv-v2
  mount: secret
  path: app/mastodon-coolmathgames/s3
  destination:
    name: mastodon-s3
    create: true
  refreshAfter: 1m
