apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-atproto-pds
spec:
  type: kv-v2
  mount: secret
  path: app/atproto-pds-sea1
  destination:
    name: pds-secrets
    create: true
  refreshAfter: 1m
