apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream_node_exporter/nodeExporter-clusterRole.yaml
- upstream_node_exporter/nodeExporter-clusterRoleBinding.yaml
- upstream_node_exporter/nodeExporter-daemonset.yaml
- upstream_node_exporter/nodeExporter-networkPolicy.yaml
# - upstream_node_exporter/nodeExporter-prometheusRule.yaml
- upstream_node_exporter/nodeExporter-service.yaml
- upstream_node_exporter/nodeExporter-serviceAccount.yaml
# - upstream_node_exporter/nodeExporter-serviceMonitor.yaml