apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream_node_exporter/nodeExporter-clusterRole.yaml
- upstream_node_exporter/nodeExporter-clusterRoleBinding.yaml
- upstream_node_exporter/nodeExporter-daemonset.yaml
- upstream_node_exporter/nodeExporter-networkPolicy.yaml
# - upstream_node_exporter/nodeExporter-prometheusRule.yaml
- upstream_node_exporter/nodeExporter-service.yaml
- upstream_node_exporter/nodeExporter-serviceAccount.yaml
# - upstream_node_exporter/nodeExporter-serviceMonitor.yaml

# scraping jobs 
- scrape_cadvisor.yaml
patches:
  - path: patch_nodeexporter_sa.yaml
helmCharts:
  - name: prometheus-smartctl-exporter
    releaseName: prometheus-smartctl-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 0.16.0
    valuesInline:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9633"
        prometheus.io/path: /metrics
