apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: erin-matrix
resources:
  - secrets-init.yaml
  - volume.yaml
  - service.yaml
  - synapse.yaml
configMapGenerator:
  - name: homeserver
    files:
      - homeserver/log.yaml
      - homeserver/homeserver.yaml