---
apiVersion: v1
kind: Service
metadata:
  name: synapse
spec:
  ports:
  - name: http
    port: 8008
  - name: metrics
    port: 8000
  selector:
    app: synapse
---
apiVersion: v1
kind: Service
metadata:
  name: mas
spec:
  selector:
    app: mas
  ports:
  - port: 8080
    name: http
