apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-cloudflare-api-token
spec:
  type: kv-v2
  mount: secret
  path: shared/cloudflare-dns
  destination:
    name: cloudflare-api-token-secret
    create: true
  refreshAfter: 30s
