---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: eightyeightthirtyone
spec:
  type: kv-v2
  mount: secret
  path: app/eightyeightthirtyone
  destination:
    name: eightyeightthirtyone-secrets
    create: true
  refreshAfter: 1m
