apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promtail
helmCharts:
  - name: promtail
    releaseName: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.17.0
    valuesFile: promtail-values.yaml
