apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-helm
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: core-services
  source:
    chart: grafana
    helm:
      valuesObject:
        persistence:
          enabled: true
          accessModes: ["ReadWriteMany"]
        extraSecretMounts:
          - name: grafana-secrets
            secretName: grafana-secrets
            defaultMode: 0440
            mountPath: /etc/secrets/grafana_secrets
            readOnly: true
        grafana.ini:
          server:
            domain: grafana.generalprogramming.org
            root_url: https://grafana.generalprogramming.org
          auth.generic_oauth:
            enabled: true
            name: General Programming SSO
            allow_sign_up: true
            client_id: $__file{/etc/secrets/grafana_secrets/oauth_client_id}
            client_secret: $__file{/etc/secrets/grafana_secrets/oauth_client_secret}
            scopes: openid email profile offline_access roles
            email_attribute_path: email
            login_attribute_path: username
            name_attribute_path: name
            groups_attribute_path: groups
            auth_url: https://sso.generalprogramming.org/realms/master/protocol/openid-connect/auth
            token_url: https://sso.generalprogramming.org/realms/master/protocol/openid-connect/token
            api_url: https://sso.generalprogramming.org/realms/master/protocol/openid-connect/userinfo
            role_attribute_path: "contains(groups[*], 'superadmin') && 'GrafanaAdmin' || contains(groups[*], 'admins') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || 'Viewer'"
            allow_assign_grafana_admin: true
        sidecar:
          datasources:
            enabled: true
            searchNamespace: ALL
          alerts:
            enabled: true
            searchNamespace: ALL
          dashboards:
            enabled: true
            searchNamespace: ALL
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - grafana.generalprogramming.org
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v6.59.0
  syncPolicy:
    automated:
      prune: true
