apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-grafana
spec:
  type: kv-v2
  mount: secret
  path: app/grafana
  destination:
    name: grafana-secrets
    create: true
  refreshAfter: 30s
