apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-grafana-ldap
spec:
  type: kv-v2
  mount: secret
  path: app/grafana-ldap
  destination:
    name: grafana-ldap
    create: true
  refreshAfter: 30s
