apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    kubernetes.io/metadata.name: vault
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: vault
    helm:
      values: |-
        global:
          enabled: false
          tlsDisable: false
          externalVaultAddr: 'https://vault-proxy.catgirls.dev:8200'

        csi:
          enabled: true

        injector:
          enabled: true
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.24.1
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector
      jsonPointers:
      - /webhooks/clientConfig/caBundle