apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-helm
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: vault
    helm:
      values: |-
        global:
          enabled: false
          tlsDisable: false
          externalVaultAddr: 'https://vault-proxy.catgirls.dev:8200'

        csi:
          enabled: true

        injector:
          enabled: true
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: "admissionregistration.k8s.io/v1"
      kind: MutatingWebhookConfiguration
      name: vault-helm-agent-injector-cfg
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
